//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 28 images.
  struct image {
    /// Image `AD_Mask`.
    static let aD_Mask = Rswift.ImageResource(bundle: R.hostingBundle, name: "AD_Mask")
    /// Image `Action_Shadow`.
    static let action_Shadow = Rswift.ImageResource(bundle: R.hostingBundle, name: "Action_Shadow")
    /// Image `Back_White`.
    static let back_White = Rswift.ImageResource(bundle: R.hostingBundle, name: "Back_White")
    /// Image `Browser_Button_Highlight`.
    static let browser_Button_Highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Button_Highlight")
    /// Image `Browser_Button`.
    static let browser_Button = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Button")
    /// Image `Browser_Icon1_Back_Highlight`.
    static let browser_Icon1_Back_Highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon1_Back_Highlight")
    /// Image `Browser_Icon1_Back`.
    static let browser_Icon1_Back = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon1_Back")
    /// Image `Browser_Icon_Action_Highlight`.
    static let browser_Icon_Action_Highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Action_Highlight")
    /// Image `Browser_Icon_Action`.
    static let browser_Icon_Action = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Action")
    /// Image `Browser_Icon_Back_Disable`.
    static let browser_Icon_Back_Disable = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Back_Disable")
    /// Image `Browser_Icon_Back_Highlight`.
    static let browser_Icon_Back_Highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Back_Highlight")
    /// Image `Browser_Icon_Back`.
    static let browser_Icon_Back = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Back")
    /// Image `Browser_Icon_Forward_Disable`.
    static let browser_Icon_Forward_Disable = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Forward_Disable")
    /// Image `Browser_Icon_Forward_Highlight`.
    static let browser_Icon_Forward_Highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Forward_Highlight")
    /// Image `Browser_Icon_Forward`.
    static let browser_Icon_Forward = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Forward")
    /// Image `Browser_Icon_Reload_Highlight`.
    static let browser_Icon_Reload_Highlight = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Reload_Highlight")
    /// Image `Browser_Icon_Reload`.
    static let browser_Icon_Reload = Rswift.ImageResource(bundle: R.hostingBundle, name: "Browser_Icon_Reload")
    /// Image `Home_Icon`.
    static let home_Icon = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Icon")
    /// Image `Home_Image_Mask_Plus`.
    static let home_Image_Mask_Plus = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Image_Mask_Plus")
    /// Image `Home_Image_Mask`.
    static let home_Image_Mask = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Image_Mask")
    /// Image `Home_Morepic`.
    static let home_Morepic = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Morepic")
    /// Image `Home_Topmask`.
    static let home_Topmask = Rswift.ImageResource(bundle: R.hostingBundle, name: "Home_Topmask")
    /// Image `Image_Preview`.
    static let image_Preview = Rswift.ImageResource(bundle: R.hostingBundle, name: "Image_Preview")
    /// Image `LaunchImage`.
    static let launchImage = Rswift.ImageResource(bundle: R.hostingBundle, name: "LaunchImage")
    /// Image `News_Image_Mask`.
    static let news_Image_Mask = Rswift.ImageResource(bundle: R.hostingBundle, name: "News_Image_Mask")
    /// Image `Splash_Image`.
    static let splash_Image = Rswift.ImageResource(bundle: R.hostingBundle, name: "Splash_Image")
    /// Image `ToolBar_Shadow`.
    static let toolBar_Shadow = Rswift.ImageResource(bundle: R.hostingBundle, name: "ToolBar_Shadow")
    /// Image `Top_Mask`.
    static let top_Mask = Rswift.ImageResource(bundle: R.hostingBundle, name: "Top_Mask")
    
    /// `UIImage(named: "AD_Mask", bundle: ..., traitCollection: ...)`
    static func aD_Mask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.aD_Mask, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Action_Shadow", bundle: ..., traitCollection: ...)`
    static func action_Shadow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.action_Shadow, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Back_White", bundle: ..., traitCollection: ...)`
    static func back_White(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.back_White, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Button", bundle: ..., traitCollection: ...)`
    static func browser_Button(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Button, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Button_Highlight", bundle: ..., traitCollection: ...)`
    static func browser_Button_Highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Button_Highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon1_Back", bundle: ..., traitCollection: ...)`
    static func browser_Icon1_Back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon1_Back, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon1_Back_Highlight", bundle: ..., traitCollection: ...)`
    static func browser_Icon1_Back_Highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon1_Back_Highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Action", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Action(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Action, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Action_Highlight", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Action_Highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Action_Highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Back", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Back, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Back_Disable", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Back_Disable(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Back_Disable, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Back_Highlight", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Back_Highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Back_Highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Forward", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Forward(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Forward, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Forward_Disable", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Forward_Disable(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Forward_Disable, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Forward_Highlight", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Forward_Highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Forward_Highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Reload", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Reload(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Reload, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Browser_Icon_Reload_Highlight", bundle: ..., traitCollection: ...)`
    static func browser_Icon_Reload_Highlight(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.browser_Icon_Reload_Highlight, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Icon", bundle: ..., traitCollection: ...)`
    static func home_Icon(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Icon, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Image_Mask", bundle: ..., traitCollection: ...)`
    static func home_Image_Mask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Image_Mask, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Image_Mask_Plus", bundle: ..., traitCollection: ...)`
    static func home_Image_Mask_Plus(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Image_Mask_Plus, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Morepic", bundle: ..., traitCollection: ...)`
    static func home_Morepic(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Morepic, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Home_Topmask", bundle: ..., traitCollection: ...)`
    static func home_Topmask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.home_Topmask, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Image_Preview", bundle: ..., traitCollection: ...)`
    static func image_Preview(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.image_Preview, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "LaunchImage", bundle: ..., traitCollection: ...)`
    static func launchImage(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.launchImage, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "News_Image_Mask", bundle: ..., traitCollection: ...)`
    static func news_Image_Mask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.news_Image_Mask, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Splash_Image", bundle: ..., traitCollection: ...)`
    static func splash_Image(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.splash_Image, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "ToolBar_Shadow", bundle: ..., traitCollection: ...)`
    static func toolBar_Shadow(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.toolBar_Shadow, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Top_Mask", bundle: ..., traitCollection: ...)`
    static func top_Mask(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.top_Mask, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R {
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard {
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}