# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZhihuDaily' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit', '~> 3.1.2'
pod 'Alamofire', '~> 4.0'
pod 'SDWebImage', '~>3.8'
pod 'R.swift'
  # Pods for ZhihuDaily

end
